services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      # Estos valores deben coincidir con tu archivo backend/.env
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: turnos
    ports:
      - "3306:3306"
    volumes:
      # Esto carga automáticamente tu base de datos al iniciar el contenedor
      - ./backend/database/database.sql:/docker-entrypoint-initdb.d/setup.sql

  backend:
    build:
      # Contexto en la raíz para que el backend pueda acceder a la carpeta /frontend
      context: .          
      # Ruta específica al Dockerfile que está dentro de la carpeta backend
      dockerfile: ./backend/Dockerfile 
    ports:
      - "3000:3000"
    env_file: 
      - ./backend/.env
    depends_on:
      - db